### ISSUE TITLE
環境佈署順序

### ISSUE THREAD

**Issue by JackKuo-tw** [MOLi-rocks/Door-RFID#1]
應該先開 venv 再安裝 package
這樣才會裝到 venv 中
```
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
```
因為通常每個專案的虛擬環境都會在該專案的資料夾底下
我們會將其統一名稱，就不用去找哪個資料夾是虛擬環境
以 venv 來命名是很不錯的選擇，記得 .gitignore 也要改一下 :)

**Comment by ast850328** [comment]
@JackKuo-tw 感謝指教 👍 
小弟不才，當時剛接觸 `virtualenv`
